name: Build
on:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-20.04
    env:
      source: "collection_src"
    steps:
      - name: checkout collection
        uses: ansible-network/github_actions/.github/actions/checkout_dependency@main
        with:
          path: ${{ env.source }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build and install collection
        id: install-collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          install_python_dependencies: true
          source_path: ${{ env.source }}
