name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main